Update Android build process in GitHub Actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,13 +19,18 @@ jobs:
 
       - name: Build Android
         run: |
-          cd android
-          chmod +x gradlew
+          GRADLE_PATH=$(find . -name gradlew | head -n 1)
+          if [ -z "$GRADLE_PATH" ]; then
+            echo "Error: gradlew not found in the zip file"
+            exit 1
+          fi
+          chmod +x "$GRADLE_PATH"
+          cd $(dirname "$GRADLE_PATH")
           ./gradlew assembleDebug
 
       - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
           name: BoyCash-App
-          path: android/app/build/outputs/apk/debug/app-debug.apk
+          path: "**/app-debug.apk"
           
